[project]
name = "nanoconfig"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.1",
    "pandas>=2.2.3",
    "plotly>=6.0.1",
    "torch>=2.6.0",
    "wandb[wandb]>=0.19.9",
]

[tool.hatch.build.targets.wheel]
packages = ["src/nanoconfig"]

[project.scripts]
clearml_task_launcher = "nanoconfig.experiment.util.clearml_launcher:run"

[project.optional-dependencies]
clearml = [
    "clearml>=1.18.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
